package main

import (
	"fmt"
	"os"

	"github.com/aosanya/mwanachama-backend-shared/spec"

	mwanachamacomm "github.com/aosanya/mwanachama-backend-comm"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: ddl <spec.json> [postgres|sqlite]")
		fmt.Fprintln(os.Stderr, "   or: ddl -instance <name> [postgres|sqlite]")
		os.Exit(2)
	}

	dialect := "postgres"
	if len(os.Args) > 3 && os.Args[1] == "-instance" {
		dialect = os.Args[3]
	} else if len(os.Args) > 2 && os.Args[1] != "-instance" {
		dialect = os.Args[2]
	}

	s, err := load(os.Args)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	fmt.Printf("-- generated by cmd/ddl\n")
	fmt.Printf("-- module %s, domain %s, instance %s, mount %s -- do not edit by hand\n\n",
		s.Module, s.Domain, s.Instance, s.MountName())
	for _, stmt := range s.DDL(dialect) {
		fmt.Println(stmt + ";")
	}
	fmt.Printf("\n-- the two notification caps are partial unique indexes Provision\n")
	fmt.Printf("-- applies after this, because the format cannot declare a condition\n")
	fmt.Printf("-- that is not `deleted`. See provision.go's syncNotificationCaps.\n")
}

func load(args []string) (*spec.Spec, error) {
	if args[1] == "-instance" {
		if len(args) < 3 {
			return nil, fmt.Errorf("ddl: -instance needs a name")
		}
		return mwanachamacomm.SpecFor(args[2])
	}
	return mwanachamacomm.LoadSpec(args[1])
}
